version: "3.4"

networks:
  dev:
    driver: bridge

services:
  chatapi:
    image: docker.io/library/chatapi
    depends_on:
      - "app_db"
    container_name: chatapi-services
    ports:
      - "5001:80"
      - "5000:443"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=ChatDbDriver;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/chatapi.pfx
    networks:
      - dev
    volumes:
      - ~/.aspnet/https:/https:ro
  
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ChatDbDriver
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:
    
